

# Set endpoints for initialization
export VITE_SERVER_ENDPOINT="https://${NAMESPACE}.server.${DOMAIN}"
export VITE_HASURA_GQL_ENDPOINT="https://${NAMESPACE}.hasura.${DOMAIN}/v1/graphql"
export HASURA_ENDPOINT="https://${NAMESPACE}.hasura.${DOMAIN}"
export HASURA_GRAPHQL_DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.${NAMESPACE}:${PG_PORT}/${POSTGRES_DB}"
export HASURA_METADATA_DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.${NAMESPACE}:${PG_PORT}/${POSTGRES_DB}"

echo "VITE_SERVER_ENDPOINT: $VITE_SERVER_ENDPOINT"
echo "VITE_HASURA_GQL_ENDPOINT: $VITE_HASURA_GQL_ENDPOINT"
echo "HASURA_ENDPOINT: $HASURA_ENDPOINT"
echo "HASURA_METADATA_DATABASE_URL: $HASURA_METADATA_DATABASE_URL"
echo "HASURA_GRAPHQL_DATABASE_URL: $HASURA_GRAPHQL_DATABASE_URL"
